<?php

/**
 * Implements hook_editor_js_settings_alter().
 */
function unl_editor_editor_js_settings_alter(array &$settings) {
  foreach (array_keys($settings['editor']['formats']) as $text_format_id) {
    if ($settings['editor']['formats'][$text_format_id]['editor'] === 'ckeditor') {
      // Add WDN classes to WYSIWYG editor so styles take effect.
      $settings['editor']['formats'][$text_format_id]['editorSettings']['bodyClass'] = 'wdn-main';
      $settings['editor']['formats'][$text_format_id]['editorSettings']['bodyId'] = 'maincontent';

      // 'edit html code' permission that governs Source WYSIWYG button access.
      if (!\Drupal::currentUser()->hasPermission('edit html code')) {
        foreach (array_keys($settings['editor']['formats'][$text_format_id]['editorSettings']['toolbar']) as $key) {
          if (is_array($settings['editor']['formats'][$text_format_id]['editorSettings']['toolbar'][$key])) {
            foreach ($settings['editor']['formats'][$text_format_id]['editorSettings']['toolbar'][$key]['items'] as $item => $label) {
              if ($label == 'Source') {
                unset($settings['editor']['formats'][$text_format_id]['editorSettings']['toolbar'][$key]['items'][$item]);
              }
            }
          }
        }
      }
    }
  }
}

/**
 * Returns path to CodeMirror, or FALSE if not found.
 */
function unl_editor_codemirror() {
  static $path;

  // Only process this once per page load.
  if (is_null($path)) {
    if (Drupal::moduleHandler()->moduleExists('libraries')) {
      $path = libraries_get_path('codemirror');
    }
    else {
      $path = 'libraries/codemirror';
    }
    $path = file_exists($path) && is_dir($path) ? $path : FALSE;
  }

  return '/' . $path;
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function unl_editor_form_node_page_edit_form_alter(array &$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  $path = unl_editor_codemirror();
  if (!empty($path)) {
    $form['#attached']['library'][] = 'unl_editor/codemirror';
    $form['#attached']['library'][] = 'unl_editor/admin';
  }
}

/**
 * Implements hook_library_info_build().
 */
function unl_editor_library_info_build() {
  $libraries = [];
  if ($path = unl_editor_codemirror()) {
    $libraries['codemirror'] = [
      'version' => 'VERSION',
      'css' => [
        'component' => [
          $path . '/lib/codemirror.css' => [],
        ],
      ],
      'js' => [
        $path . '/lib/codemirror.js' => [],
        $path . '/mode/css/css.js' => [],
        'js/unl_editor.js' => [],
      ],
      'dependencies' => [
        'core/jquery',
        'core/drupal',
      ],
    ];
  }
  return $libraries;
}
