<?php

/**
 * Implements hook_editor_js_settings_alter().
 */
function unl_editor_editor_js_settings_alter(array &$settings) {
  foreach (array_keys($settings['editor']['formats']) as $text_format_id) {
    if ($settings['editor']['formats'][$text_format_id]['editor'] === 'ckeditor') {
      // Add WDN classes to WYSIWYG editor so styles take effect.
      $settings['editor']['formats'][$text_format_id]['editorSettings']['bodyClass'] = 'wdn-main';
      $settings['editor']['formats'][$text_format_id]['editorSettings']['bodyId'] = 'maincontent';

      // 'edit html code' permission that governs Source WYSIWYG button access.
      if (!\Drupal::currentUser()->hasPermission('edit html code')) {
        foreach (array_keys($settings['editor']['formats'][$text_format_id]['editorSettings']['toolbar']) as $key) {
          if (is_array($settings['editor']['formats'][$text_format_id]['editorSettings']['toolbar'][$key])) {
            foreach ($settings['editor']['formats'][$text_format_id]['editorSettings']['toolbar'][$key]['items'] as $item => $label) {
              if ($label == 'Source') {
                unset($settings['editor']['formats'][$text_format_id]['editorSettings']['toolbar'][$key]['items'][$item]);
              }
            }
          }
        }
      }
    }
  }
}
